[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NETLIFY = "true"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
